{
  parser: "@typescript-eslint/parser",
  plugins: ["@typescript-eslint"],
  extends:
    [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:prettier/recommended",
    ],
  rules:
    {
      "quotes": [2, "double"],
      "indent": ["off", 2, { "SwitchCase": 1 }],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
}
